version: '3'
services:
  server:
    build: ./server/.
    depends_on:
      localstack:
        condition: service_started
    ports:
      - 5000:5000
    volumes:
      - ./server/.:/usr/src/app
      - /usr/src/app/node_modules

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4583:4567-4583"
      - "8080:8080"
    environment:
      - SERVICES=dynamodb
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-southeast-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
